# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
services:
    Buddy\Repman\Service\AmazonWebServices\S3AdapterFactory:
        arguments:
            - '%env(STORAGE_AWS_REGION)%'
            - '%env(bool:STORAGE_AWS_OPAQUE_AUTH)%'
            - '%env(STORAGE_AWS_KEY)%'
            - '%env(STORAGE_AWS_SECRET)%'

    Aws\S3\S3Client:
        lazy: true
        factory:
            - '@Buddy\Repman\Service\AmazonWebServices\S3AdapterFactory'
            - create

flysystem:
    storages:
        storage.local.proxy:
            adapter: 'local'
            options:
                directory: '%dists_dir%'

        storage.local.repo:
            adapter: 'local'
            options:
                directory: '%repo_dir%'

        storage.s3.proxy:
            adapter: 'aws'
            options:
                client: 'Aws\S3\S3Client'
                bucket: '%env(STORAGE_AWS_BUCKET)%'
                prefix: '%dists_dir%'

        storage.s3.repo:
            adapter: 'aws'
            options:
                client: 'Aws\S3\S3Client'
                bucket: '%env(STORAGE_AWS_BUCKET)%'
                prefix: '%repo_dir%'

        repo.storage:
            adapter: 'lazy'
            options:
                source: '%env(STORAGE_SOURCE)%.repo'

        proxy.storage:
            adapter: 'lazy'
            options:
                source: '%env(STORAGE_SOURCE)%.proxy'
